### ISSUE TITLE
403 Forbidden on iChef images

### ISSUE THREAD

**Issue by ChrisBAshton** [iplayer/hiring#1]
I'm completing the [a-z coding challenge](https://github.com/iplayer/hiring/blob/master/azListing.md) but the images returned in the JSON feed are unreachable.

The following URLs (and any other "recipes" I provide) are giving me a 403 Forbidden error when accessed directly in the browser:
- http://ichef.bbci.co.uk/images/ic/{recipe}/p01hhrgb.jpg
- http://ichef.bbci.co.uk/images/ic/100/p01hhrgb.jpg
- http://ichef.bbci.co.uk/images/ic/624/p01hhrgb.jpg

This may have been overlooked when the challenge was first created. Could someone let me know if I am missing something? Thanks

**Comment by middric** [comment]
`{recipe}` can be replaced with a 16:9 dimension such as `160x90`:

http://ichef.bbci.co.uk/images/ic/160x90/p01hhrgb.jpg
